### ISSUE TITLE
Transfer repository

### ISSUE THREAD

**Issue by mainland** [mainland/hiw#4]
We should transfer this repository somewhere more appropriate. Is @haskell the right place, @nomeata @goldfirere @bgamari?

**Comment by nomeata** [comment]
https://github.com/haskell/ sounds reasonable. One of these owners probably have to act on that: https://github.com/orgs/haskell/people?query=role%3Aowner

**Comment by bgamari** [comment]
I agree that @haskell is a reasonable neutral location. @mainland, if you grant me access to this repository I can take care of transferring it.

**Comment by mainland** [comment]
Since this is a personal repository, only I can transfer it. Would you like me to transfer it directly to @haskell, or did you mean for me to transfer it to you, @bgamari?

**Comment by bgamari** [comment]
Feel free to transfer it directly to @haskell. I merely meant to suggest that you are free to transfer it to me and leave any other arrangements to me if you are unable to do the transfer directly.

**Comment by xnning** [comment]
Any progress on the migration? Shall I use it to upload HIW'21 info (and to add HIW'22 chair @serras)?

**Comment by mainland** [comment]
Please talk to @bgamari —I don't recall what happened, but I thought I had transferred this to him long ago. In any case, he already has a `hiw` repository, so I can't transfer this one to him. I also don't have permission to transfer it to @haskell.

**Comment by goldfirere** [comment]
The rules are spelled out in https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository. To transfer into an organization (such as `/haskell`), you need to have repo-creation rights in the org. The set of such people is listed at https://github.com/orgs/haskell/people?query=role%3Aowner. I don't see anyone with recent HIW affiliation there, so we'll need to reach out to one of them to help us with this. I somewhat arbitrarily propose @jaspervdj.

So, @jaspervdj: would it be OK if we house the `hiw` repo for organizing Haskell Implementors' Workshop within the github.com/haskell org? If so, would you consent to receiving a transfer from @mainland and then transferring on to the `/haskell` org? Thanks!

**Comment by jaspervdj** [comment]
`/haskell` sounds like a reasonable location.  I've temporarily granted @mainland administration privileges there so he can move this repository.

**Comment by mainland** [comment]
Thanks, @jaspervdj!
